training_pipeline_config:
  pipeline_name: credit_classification
  artifact_dir: artifact


data_ingestion_config:
  ingested_train_dir: train
  ingested_test_dir: test

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  status_file: str


